#@ load("@ytt:overlay", "overlay")

#@ for i in range(3):
---
apiVersion: v1
kind: Namespace
metadata:
  name: #@ i
#@ end

#@ for i in range(3):
---
item: #@ i
#@ end

#@ def x(left):
namespace: #@ left["metadata"]["name"]
#@ end

#@overlay/match by=overlay.subset({"kind": "Namespace"}), expects="0+"
#@overlay/insert after=True, via=x
---

#@overlay/match by=lambda i, left, right: "item" in left, expects="0+"
#@overlay/insert after=True, via=lambda left: {"from_item": left["item"], "after": True}
---
hello: max
